# -*- coding: utf-8 -*-
"""ASSIGNMENT1_LIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15SnbSz6wAMs2Ful2cZnZoa9jMRndT5oE

1. Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

	Given List:

	list1 = ["M", "na", "i", "Ra"]
	list2 = ["y", "me", "s", "hul"]

	Output:

	[['M','y'], ['na', me'], ['i', 's'], ['Ra', 'hul']]
"""

# creating lists
list1 = ["M", "na", "i", "Ra"]
list2 = ["y", "me", "s", "hul"]
# adding both lists values by index in new list
new_list= [[list1[0],list2[0]]
           ,[list1[1],list2[1]]
           ,[list1[2],list2[2]]
           ,[list1[3],list2[3]]
           ]
# printing new_list
print(new_list)

"""2. Write a program to add item 7000 after 6000 in the following Python List

	list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
	Output:

	[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]
"""

# creating list
list1 =  [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
# adding new element by index
list1[2][2].append(7000)
# printing list
print(list1)

"""3. Suppose you are given a list of candy and another list of same size representing no of items of respective candy.

	i.e -

	candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
	no_of_items = [10,20,34,74,32]
	Write a program to show no. of items of each candy type.

	Output:

	Jelly Belly-10
	Kit Kat-20
	Double Bubble-34
	Milky Way-74
	Three Musketeers-32
"""

candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]

# iterating value one by one till last value of list i.e candy_list
for i in range(len(candy_list)):
  # printing both lists together with '-' hyphen
  print(candy_list[i],"-",no_of_items[i],end=" ")

"""4. Running Sum on list Write a program to print a list after performing running sum on it.

	i.e:

	Input:

	list1 = [1,2,3,4,5,6]
	Output:

	[1,3,6,10,15,21]
"""

list1 = [1,2,3,4,5,6]
# creating empty list to append/insert resulted values later
new_list = []

# assigning 0 to variable to add one by one element
sum = 0

# iterating value one by one till end of last value of list
for i in range(len(list1)):
  # adding one by one value from list
  sum = sum + list1[i]
  # append result in new list
  new_list.append(sum)


print(new_list)

"""5. You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater and itself.

	i.e. Say given list is [2,4,6,10,1] resultant list will be [22,20,10,23].

	For 1st element 2 ->> these are greater (4+6+10) values and 2 itself so on adding becomes 22.

	For 2nd element 4 ->> greater elements are (6, 10) and 4 itself, so on adding 20

	like wise for all other elememts.

	[2,4,6,10,1]-->[22,20,16,10,23]
"""

l = [2,4,6,10,1]

# creating new empty list to append resulted values later
new_list = []

# iterating value one by one till end of last value of list
for i in range(len(l)):
  # assigning current value into variable
  cur_item = l[i]
  # assigning 0 to variable to add one by one element
  sum = 0
  # iterating value one by one till end of last value of list
  for j in range(len(l)):
    # checking values one by one if they are greater than current item(cur_item)
    if l[j] > cur_item:
      # if found greater values then adding one by one
      sum = sum + l[j]
  # inserting resulted values into new list(values which greater than current item and current item itself)
  new_list.append(sum + cur_item)


print(new_list)

"""6. Find list of common unique items from two list. and show in increasing order

	Input

	num1 = [23,45,67,78,89,34]
	num2 = [34,89,55,56,39,67]
	Output:

	[34, 67, 89]
"""

num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
new_list = []

# iterating value one by one till end of last value of list(num1)
for i in range(len(num1)):
  # iterating value one by one till end of last value of list(num2)
  for j in range(len(num2)):
    # checking values one by one from both lists if they are equal
    if num1[i] == num2[j]:
      # if equal values found then adding into new list
      new_list.append(num1[i])
      # sorting list in asending order
      new_list.sort()

print(new_list)

"""7. Sort a list of alphanumeric strings based on product value of numeric character in it. If in any string there is no numeric character take it's product value as 1.

	Input:

	['1ac21', '23fg', '456', '098d','1','kls']
	Output:

	['456', '23fg', '1ac21', '1', 'kls', '098d']
"""

def sort_alpha_numeric_list(lst):
    # assigning 1 as product value
    p = 1
    has_digit = False

    # Iterating one by one character to find it has digit and multiply digits
    for char in lst:
        if char.isdigit():
            p = p * int(char)
            has_digit = True

    # If no digits found in string, the product remains 1
    return p


alpha_numeric_list = ['1ac21', '23fg', '456', '098d', '1', 'kls']

# Sorting in descending order
sorted_data = sorted(alpha_numeric_list, key=sort_alpha_numeric_list, reverse=True)
print(sorted_data)

"""8. Write a program that can find the max number of each row of a matrix
	Example:

	Input:

	[[1,2,3],[4,5,6],[7,8,9]]
	Output:

	[3,6,9]
"""

lst = [[1,2,3],[4,5,6],[7,8,9]]
new_list = []

# iterating one one element till last value of list
for i in range(len(lst)):
  # adding max values one by one into new list
  new_list.append(max(lst[i]))

print(new_list)

"""9. Shortlist Students for a Job role Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

	Show every students record in form of tuples if matches all required criteria.

	It is assumed that there will be only one primry skill.

	If no such candidate found, print No such candidate

	Input:

	Enter No of records- 2
	Enter Details of student-1
	Enter Student name- Manohar
	Enter Higher Education- B.Tech
	Enter Primary Skill- Python
	Enter Year of Graduation- 2022
	Enter Details of student-2
	Enter Student name- Ponian
	Enter Higher Education- B.Sc.
	Enter Primary Skill- C++
	Enter Year of Graduation- 2020

	Enter Job Role Requirement
	Enter Skill- Python
	Enter Higher Education- B.Tech
	Enter Year of Graduation- 2022
	Output

	('Manohar', 'B.tech', 'Python', '2022')
"""

# function defintion
def shortlist_students():
  no_of_rec = int(input("Enter No of records- "))
  # creating empty list to store data
  students = []

  for i in range(no_of_rec):
    # input data
    print("Enter Details of student =", i+1)
    name = input("Enter Student's name- ")
    hedu = input("Enter Higher Education- ")
    ps = input("Enter Primary Skill- ")
    yog = int(input("Enter Year of Graduation- "))

    # append all entered data into list as tuple
    students.append((name, hedu, ps, yog))

  # search candidates input data
  print("\nEnter Job Role Requirement\n")
  job_role = input("Enter Skill- ")
  job_hedu = input("Enter Higher Education- ")
  job_yog = int(input("Enter Year of Graduation- "))

  print("\nThe Candidates Are: ")
  found = False
  for i in students:
    # unpacking tuple for easy comparison
    name,hedu,ps,yog = i
    # checking if data is found or not
    if ps == job_role and hedu == job_hedu and yog == job_yog:
      print(i)
      found = True

    # for i in students:
    #   if i[2] == job_role and i[1] == job_hedu and i[3] == job_yog:
    #     print(i)
    #     found = True

  # if data is not found
  if found == False:
    print("No such Candidates")



# calling function
shortlist_students()

"""10. Write a program to find set of common elements in three lists using sets.

	Input : ar1 = [1, 5, 10, 20, 40, 80]
			ar2 = [6, 7, 20, 80, 100]
			ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

	Output : [80, 20]
"""

ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

new_list = []

for i in range(len(ar1)):
  for j in range(len(ar2)):
    for k in range(len(ar3)):
      # checking values one by one if same or not in all three lists
      if ar1[i] == ar2[j] == ar3[k]:
        # inserting same values in new list
        new_list.append(ar1[i])
        # sorting in desc order
        new_list.sort(reverse=True)

print(new_list)

"""11. Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

	Input:

	Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
	Output:

	No of unique vowels-6
"""

Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
new_set =  set(Str1)
print(new_set)
vowel = {'a','e','i','o','u','A','E','I','O','U'}
count = 0

# s[i] (cannot do this) - set index has no any fixed position so, we have to sort it to iterate the items
# To iterate in a predictable order (e.g., alphabetical or numerical), use the sorted() function, which returns a sorted list of the set's items.
for i in sorted(new_set):
  # checking one by one character from set is present in vowel list or not
  if i in vowel:
    # if present counting one by one
    count += 1

print("No of Unique vowels-",count)


# another way
# using enumerate() - If you need a counter while iterating, use the enumerate() function
# for index,item in enumerate(new_set):
#   if item in vowel:
#     count+=1
# print("No of Unique vowels-",count)

"""12. Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using list-comprehension.
	Example 1:

	Input:

	lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
	lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
	Output:

	[9, 10, 4, 5]
	Example 2:

	Input:

	lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
	lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
	Output:

	[9, 11, 26, 28]

"""

# without list comprehension
# lst1 = [15, 9, 10, 56, 23, 78, 5, 4, 9]
# lst2 = [9, 4, 5, 36, 47, 26, 10, 45, 87]
# new_list = []
# for i in range(len(lst1)):
#   for j in range(len(lst2)):
#     if lst1[i] == lst2[j]:
#       new_list.append(lst1[i])
# print(set(new_list))

# Using list Comprehension
lst1 = [15, 9, 10, 56, 23, 78, 5, 4, 9]
lst2 = [9, 4, 5, 36, 47, 26, 10, 45, 87]

# checking common values one by one and storing into variable
intersect = [i for i in lst1 if i in lst2]

# converting into set to show unique values
print(set(intersect))

"""13. Convert a list of Tuples into Dictionary.
	Example 1:

	Input:

	[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
	Output:

	{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
	Example 2:

	Input:

	[('A', 1), ('B', 2), ('C', 3)]
	Output:

	{'A': [1], 'B': [2], 'C': [3]}
"""

a = [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
# converting list of tuple into dictionary
b = dict(a)
print(b)

lt = [('A', 1), ('B', 2), ('C', 3)]
# converting list of tuple into dictionary
d = dict(lt)
print(d)

"""14. Write a Python function that takes a list and returns a new list with unique elements of the first list.
	Exercise 1:

	Input:

	[1,2,3,3,3,3,4,5]
	Output:

	[1, 2, 3, 4, 5]

"""

# function creation
def Unique_Items():
  lst = [1,2,3,3,3,3,4,5]
  new_list = []

  for i in range(len(lst)):
    # checking if value of list(lst) one by one is not present in new list
    if lst[i] not in new_list:
      # if not present then inserting into new list
      new_list.append(lst[i])
  return new_list

# function calling
Unique_Items()

"""15.  Write a Python program to print the even numbers from a given list.
		Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
		Expected Result : [2, 4, 6, 8]
"""

sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
resulted_list = []

for i in range(len(sample_list)):
  # checing values one by one is even or not
  if sample_list[i] % 2 == 0:
    # if found even values then inserting into new list(resulted_list)
    resulted_list.append(sample_list[i])

print(resulted_list)

"""16. Write a Python function to check whether a number is perfect or not.¶
	A Perfect number is a number that is half the sum of all of its positive divisors (including itself).

	Example :

	The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6.
	Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6.

	The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.
"""

def perfect_number(num):
  sum = 0

  # iterating value from 1 to num
  for i in range(1,num):
    # checking number is divisible or not
    if num % i == 0:
      # if number is divisible then adding one by one into sum
      sum += i

#  checking if value of sum is equal to number
  if sum == num:
    # if equal
    print(f"{num} is a perfect number")
  else:
    # if not equal
    print(f"{num} is not perfect number")

# calling function
perfect_number(28)

"""17. Write a Python function to concatenate any no of dictionaries to create a new one.
	Sample Dictionary :
	dic1={1:10, 2:20}
	dic2={3:30, 4:40}
	dic3={5:50,6:60}
	Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
"""

dict1 = {1:10, 2:20}
dict2 = {3:30, 4:40}
dict3 ={5:50,6:60}

dict = {}
# adding all three dictionary values into empty dictionary
dict.update(dict1)
dict.update(dict2)
dict.update(dict3)
print(dict)

"""18. Write a python function that receives a list of integers and prints out a histogram of bin size 10

	Input:
	[13,42,15,37,22,39,41,50]
	Output:
	{11-20:2,21-30:1,31-40:2,41-50:3}
"""

def print_histogram(lst):
    if not lst:
        return {}

    # Sorting data to make it easy to range it out
    sorted_data = sorted(lst)

    # Calculating start and end boundaries for the bins
    # For example, 13 starts at 11 (10 + 1)
    start = (min(sorted_data) - 1) // 10 * 10
    end = (max(sorted_data) + 9) // 10 * 10

    histogram = {}

    # Iterate through the range and create bins
    for i in range(start, end, 10):
        bin_label = f"{i + 1}-{i + 10}"
        # Count elements that fall within the current bin
        count = len([x for x in sorted_data if i < x <= i + 10])

        # Only add bins that have at least one element
        if count > 0:
            histogram[bin_label] = count

    return histogram


sample_list = [13, 42, 15, 37, 22, 39, 41, 50]
print_histogram(sample_list)