# -*- coding: utf-8 -*-
"""ASSIGNMENT_FUNCTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCockXnrLO7NMkNH8LyWjXyr-c6lP6Nc

1. Write a Python function to find the maximum of three numbers.
"""

def max_number(a,b,c):
  # checking if a is greater than b
  if a > b:
    print(a,"is maximum")
    # return f"{a} is maximum"
    # checking b is greater than c
  elif b > c:
    print(b,"is maximum")
  else:
    # if a and b is not greater
    print(c,"is maximum")


max_number(10,20,30)
max_number(45,23,6)

"""2. Write a Python function to sum all the numbers in a list.

	Sample List : (8, 2, 3, 0, 7)
	Expected Output : 20
"""

def sum_of_elements(my_list):
  sum = 0

  # iterating values one by one till last element of list
  for i in my_list:
    # adding one by one value into sum
    sum = sum + i
    # returning total sum
  return sum

# input list
sample_list = [8,2,3,0,7]
print(sum_of_elements(sample_list))


# another way

# using args
def sum_all(*args):
    return sum(args)

print(sum_all(8,2,3,0,7))

"""3. Write a Python function to multiply all the numbers in a list.

	Sample List : (8, 2, 3, -1, 7)
	Expected Output : -336
"""

def multiple_of_elements(my_list):
  mul = 1

  # iterating one by one value till last element of list
  for i in my_list:
    # multiplying value one by one into mul variable
    mul = mul * i
  # returning multiplication
  return mul

# input data
sample_list = [8,2,3,-1,7]
# calling function
multiple_of_elements(sample_list)

"""4. Write a Python function to reverse a string.

	Sample String : "1234abcd"
	Expected Output : "dcba4321"
"""

def reverse_string(my_string):
    return my_string[::-1]

print(reverse_string("1234abcd"))


# another way

def reverse_text(my_string):
  rev_text = ""
  # iterating char by char till end of string
  for char in my_string:
    #adding ont by one characters in variable rev_text
    rev_text = char + rev_text
  return rev_text

print(reverse_text("1234abcd"))

"""5. Write a Python function to check whether a number falls within a given range."""

def given_range(start, end):
  print(f"The range is between {start} and {end}")
  # input number to check whether a number falls within a given range
  num = int(input("Enter a number to check whether it is in a given range or not: "))

  # checking input number is in range
  if num in range(start, end):
    # it it is in range will return this
    return f"{num} is in range"
    # if not in range
  else:
    return f"{num} is not in range"

# calling function
# given_range(1,10)
given_range(25,50)

"""6. Write a Python function that accepts a string and counts the number of upper and lower case letters.
	Sample String : 'The quick Brow Fox'
	Expected Output :
	No. of Upper case characters : 3
	No. of Lower case Characters : 12
"""

def string_upper_lower(my_string):
  upper_count = 0
  lower_count = 0

  # iterating one by one character till last character of string
  for char in my_string:
    # checking characters are in upper case
    if char.isupper():
      # counting one by one upper case characters
      upper_count += 1
      #also checking characters are in lower case
    elif char.islower():
      # counting one by one lower case characters
      lower_count += 1
      # returning result
  return f"No. of Lower case characters: {lower_count} No of Upper case characters: {upper_count}"


# calling function
string_upper_lower("The quick Brow Fox")

"""7. Write a Python function that takes a list and returns a new list with distinct elements from the first list.

	Sample List : [1,2,3,3,3,3,4,5]
	Unique List : [1, 2, 3, 4, 5]
"""

def distinct_list(my_list):
  new_list = []

  # iterating elements one by one till last element of list
  for i in my_list:
    # adding into new list
    new_list.append(i)
  return new_list

# input data
sample_list = [1,2,3,3,3,3,4,5]

# Converting a list to a set automatically removes duplicates because sets only contain unique elements.
# calling function
print(distinct_list(set(sample_list)))

# another way
#dict.formkeys()- This method creates a dictionary using list elements as keys (which are inherently unique) and then converts it back to a list.
print(distinct_list(dict.fromkeys(sample_list)))

"""
8. Write a Python function that checks whether a passed string is a palindrome or not.

	Note: A palindrome is a word, phrase, or sequence that reads the same backward as forward, e.g., madam or nurses run."""

def string_palindrome(my_string):
  # assigning empty string
  str = ""

  # iterating character by character till last character of string
  for char in my_string:
    # adding one by one character into str
    str = char + str
    # checking both stringa are matching
  if my_string == str:
    # if matches it returns this statement
    return f"{my_string} is palindrome"
  else:
    # if not matches it returns this statement
    return f"{my_string} is not palindrome"


# calling function
# string_palindrome("madam")
string_palindrome("nursesrun")

"""9. Write a Python program that accepts a hyphen-separated sequence of words as input and prints the words in a hyphen-separated sequence after sorting them alphabetically.

	Sample Items : green-red-yellow-black-white
	Expected Result : black-green-red-white-yellow
"""

def hyphen_separated_words(my_string):
  # spliting input string by '-' character
  break_string = my_string.split("-")
  # sorting in ascending order
  break_string.sort()
  # joining with '-' character after sorting
  joint_myString = "-".join(break_string)
  # returning result
  return joint_myString


# calling function
hyphen_separated_words("green-red-yellow-black-white")

"""10. Write a Python program to detect the number of local variables declared in a function."""

def local_var_count(a,b):
  x = 10
  y = 15
  str = "Hello! Good morning"
  # return x+y

  # co_nlocals Attribute: returns the total count of all local variables used by the function.
  # To see the actual names of the local variables, you can use the __code__.co_varnames attribute.
  print(local_var_count.__code__.co_varnames)
  local_count = local_var_count.__code__.co_nlocals
  return f"local variables are {local_count}"


# calling function
local_var_count(10,15)

"""11. Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument, also create a lambda function that multiplies argument x with argument y and prints the result.

	Sample Output:
	25
	48
"""

# Lambda function to add 15 to a given number
add = lambda x: x + 15
print(add(10))

# Lambda function to multiply x with y
multiply = lambda x,y: x * y
print(multiply(8,6))

"""12. Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.

	Sample Output:
	Double the number of 15 = 30
	Triple the number of 15 = 45
	Quadruple the number of 15 = 60
	Quintuple the number 15 = 75
"""

def multiply_value(num):
  # lambda function to multiply numbers
  mul = lambda x: x * num
  print("Double the number of",num,"=",mul(2))
  print("Triple the number of",num,"=",mul(3))
  print("Quadruple the number of",num,"=",mul(4))
  print("Quintuple the number of",num,"=",mul(5))

multiply_value(15)



# another way way

#lambda within lambda function
#function that  multiplying numbers
multiply_number = lambda n : (lambda x: x * n)

# function that doubles the number
double = multiply_number(2)
print(double(15))

# function that triples the number
triple = multiply_number(3)
print(triple(15))

# function that Quadruple the number
Quadruple = multiply_number(4)
print(Quadruple(15))

# function that Quintuple the number
Quintuple = multiply_number(5)
print(Quintuple(15))

"""13. Write a Python program to sort a list of tuples using Lambda.

	Original list of tuples:
	[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
	Sorting the List of Tuples:
	[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]
"""

def tuple_element_sort(my_list):
  # sorting marks wise by its index
  my_list.sort(key = lambda x: x[1])
  return my_list

# calling function
tuple_element_sort([('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)])

"""14. Write a Python program to sort a list of dictionaries using Lambda.

	Original list of dictionaries :
	[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
	Sorting the List of dictionaries :
	[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}]
"""

def sort_dictionary(my_list):
  # sorting by color in ascending order
  sorted_data = sorted(my_list, key=lambda x: x['color'])
  # returning sorted data
  return sorted_data

a =  [{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'},{'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
sort_dictionary(a)

"""15. Write a Python program to filter a list of integers using Lambda.

	Original list of integers:
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	Even numbers from the said list:
	[2, 4, 6, 8, 10]
	Odd numbers from the said list:
	[1, 3, 5, 7, 9]
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# calculating even numbers from list
filter_even_numbers = list(filter(lambda num: num % 2 == 0, numbers))

# calculating odd numbers from list
filter_odd_numbers = list(filter(lambda num: num % 2 != 0, numbers))

print("Original list of integers: ",numbers)
print("Even numbers from said list: ",filter_even_numbers)
print("Odd numbers from said list: ",filter_odd_numbers)

"""16. Write a Python program to square and cube every number in a given list of integers using Lambda.

	Original list of integers:
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	Square every number of the said list:
	[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
	Cube every number of the said list:
	[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
"""

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# calculating square of every element
filter_square_numbers = list(map(lambda s: s**2, nums))

# calculating cube of every element
filter_cube_numbers = list(map(lambda c: c**3,nums))

print("Square every number of the said list: ",filter_square_numbers)
print("Cube every number of the said list: :",filter_cube_numbers)

"""17. Write a Python program to find if a given string starts with a given character using Lambda."""

# lambda function that checks given string starts with given character or not
given_str = lambda str1,ch: True if str1.startswith(ch) else False

print(given_str("Hello","H"))
print(given_str("hello",'p'))

"""18. Write a Python program to rearrange positive and negative numbers in a given array using Lambda.

	Original arrays:
	[-1, 2, -3, 5, 7, 8, 9, -10]
	Rearrange positive and negative numbers of the said array:
	[2, 5, 7, 8, 9, -10, -3, -1]


"""

# lambda function that checking which numbers are positive and negative and sorting accordingly
rearrange_numbers = lambda num: [i for i in num if i >= 0] + [i for i in num if i < 0]

print(rearrange_numbers([-1, 2, -3, 5, 7, 8, 9, -10]))

"""19. Write a Python program to count the even and odd numbers in a given array of integers using Lambda.

	Original arrays:
	[1, 2, 3, 5, 7, 8, 9, 10]
	Number of even numbers in the above array: 3
	Number of odd numbers in the above array: 5
"""

org_array = [1, 2, 3, 5, 7, 8, 9, 10]

# calculationg length of even numbers by filtering out from list
no_of_even_numbers = len(list(filter(lambda x: x % 2 == 0,org_array)))
print("Number of even numbers in above array: ",no_of_even_numbers)

# calculating length of odd numbers by filtering out from list
no_of_odd_numbers = len(list(filter(lambda x: x % 2 != 0, org_array)))
print("Number of odd numbers in above array: ",no_of_odd_numbers)

"""20. Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda.

	Orginal list:
	[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
	Numbers of the above list divisible by nineteen or thirteen:
	[19, 65, 57, 39, 152, 190]
"""

org_list =  [19, 65, 57, 39, 152, 639, 121, 44, 90, 190]

# filtering out numbers which are divisible by 13 or 19
div_numbers = list(filter(lambda x: x % 13 ==0 or x % 19 == 0, org_list))

print(div_numbers)

"""21. Write a Python program to check whether a given string contains a capital letter, a lower case letter, a number and a minimum length using lambda."""

# checking given string has upper case, lower case, a digit or length has greater than 7 or not
str = lambda str: (
                  any (c.isupper() for c in str) and
                  any (c.islower() for c in str) and
                  any (c.isdigit() for c in str) and
                  len(str) >= 7
              )

print(str("Hello123"))
print(str("welcome1"))

