# -*- coding: utf-8 -*-
"""Exception-Handling-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ulf1LOnf0w3uJz1C3wqAa4GVaRCRUfb

1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.
"""

def divide_numbers(a,b):
  try:
    # code that might raise an error
    div = a/b
    print("Division is : ",div)
  except ZeroDivisionError:
    print("Error: Divisible by zero is not allowed")

divide_numbers(10,5)
divide_numbers(10,0)

"""2. Write a Python program that prompts the user to input an integer and raises a ValueError exception if the input is not a valid integer."""

def get_integer():
  try:
    num = int(input("Enter any number "))
    print(num)
  except ValueError:
    print("Error: Input is not a valid integer")

get_integer()

"""3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist."""

def open_file(filename):
  try:
    with open(filename, 'r'):
      print(f"File '{filename}' opened successfully")
  except FileNotFoundError:
    print(f"Error: File '{filename}' not found")


# open_file("sample_data/mnist_test.csv")
open_file("movies.json")

"""4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception if the inputs are not numerical."""

def check_number(val):
    if not val.isnumeric():
        raise TypeError("Inputs are not numerical!")
    return int(val)

try:
    num1 = input("Enter first number: ")
    num2 = input("Enter second number: ")

    check_number(num1)
    check_number(num2)
    print(num1+num2)

except TypeError as e:
    print(f"Caught an error: {e}")

"""5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue."""

def open_file(filename):
  try:
    with open(filename, 'r') as f:
      print(f"File '{filename}' opened successfully")
  except PermissionError:
    print(f"Error: Permission denied to open file '{filename}'")

open_file("sample_data/mnist_test.csv")

"""6. Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range."""

try:
  lst = [1,2,3,4,5,6]
  print(lst[10])
except IndexError:
  print("Error: Index is out of range")

"""7. Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error."""

try:
  div = 4/0
  print(div)
except ArithmeticError as e:
  print(f"Error: Arithmetic error. Details {e}")