# -*- coding: utf-8 -*-
"""File-Handling-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L708f6k43z8Q0CeD67qn9j2H9ach0Cux

1. Write a Python program to read an entire text file.
"""

# function to read data from file
def read_file(filename):
  with open(filename, 'r') as f:
    lines = f.read()
    print(lines)

read_file('movies.txt')

"""2. Write a Python program to read first n lines of a file."""

# function to read first n lines

def read_first_n_lines(filename, n):

  with open(filename, 'r') as f:
    for i in range(n):
      line = f.readline()

      if not line:
        # will stop if end of file is reached
        break
      print(line, end='')

# calling function
read_first_n_lines('movies.txt', 5)

"""3. Write a Python program to append text to a file and display the text."""

# to write data in file(if file doen't exist it creates and if exists then it overwrites data)
def write_file(filename):
  with open(filename, 'a') as f:
    f.write("This is a sample file to practice")

  # to read data from file
  with open(filename, 'r') as f:
    print(f.read())


write_file("sample.txt")

"""4. Write a Python program to read last n lines of a file."""

# function to read last n lines from file

def read_last_n_lines(filename, n):

  with open(filename, 'r') as f:
    # read all lines
    line = f.readlines()
    # negative slicing to get last lines
    last_lines = line[-n:]
    # iterating line by line data
    for line in last_lines:
      # printing it
      print(line, end='')

# calling function
read_last_n_lines("movies.txt",6)

"""5. Write a Python program to read a file line by line and store it into a list."""

def read_file_line_by_line(filename):
  lst = []
  with open(filename, 'r') as f:
    # lines = f.readline()
    for line in f:
      lst.append(line)
    print(lst, end='')

read_file_line_by_line("sample.txt")

"""6. Write a Python program to read a file line by line store it into a variable."""

def read_file_line_by_line(filename):
  var = ""
  with open(filename, 'r') as f:
    for line in f:
      var += line
    print(var)

read_file_line_by_line("sample.txt")

"""7. Write a python program to find the longest words."""

def find_longest_word(filename):

  # reads file
  with open(filename, 'r') as f:
    # splits into words
    words = f.read().split()

    # find max length from list words
    # max function finds longest word from list and len() returns count of that word
    max_len = len(max(words, key=len))

  # retruns all words that matches with max_len
  return [word for word in words if len(word) == max_len]

find_longest_word("sample.txt")

"""8. Write a Python program to count the number of lines in a text file."""

def count_lines(filename):
  with open(filename, 'r') as f:
    # reads line by line
    lines = f.readlines()
    # prints line count
    print(f"Total lines count in {filename} is : {len(lines)}")

count_lines("sample.txt")
count_lines("movies.txt")

"""9. Write a Python program to count the frequency of words in a file."""

# counter stores elements as dictionary keys and their count as values
from collections import Counter

def frequency_count(filename):
  with open(filename, 'r') as f:
    # Read file, convert to lowercase, and split into words
    words = f.read().lower().split()
    # Count frequencies
    return Counter(words)


file_name = 'sample.txt'  # Ensure this file exists in your directory
frequencies = frequency_count(file_name)
print(frequencies)

"""10. Write a Python program to get the file size of a plain file."""

import os

def file_size(filename):
  # checks if file is exist or not
  if os.path.isfile(filename):
    # returns size of file in bytes
    size = os.path.getsize(filename)
    print(f"The size of {filename} is: {size} bytes")

file_size("sample.txt")
file_size("movies.txt")

"""11. Write a Python program to write a list to a file."""

def write_list_to_file(filename, lst):

  # writes list data
  with open(filename, 'w') as f:
    # writes one by one at new line
    for item in lst:
      f.write(f"{item}\n")
      print(item)


write_list_to_file("add_list_data.txt",["101","vrushali","28"])

"""12. Write a Python program to copy the contents of a file to another file ."""

def copy_content(source_file, destination_file):
  # reads data from sorce file
  with open(source_file, 'r') as sf:
    # writes into destination file
    with open(destination_file, 'w') as df:
      for line in sf:
        df.write(line)
        print(line)

copy_content('sample.txt','new_sample.txt')

"""13. Write a Python program to read a random line from a file."""

import random

def read_random_line(filename):
  with open(filename, 'r') as f:
    lines = f.readlines()
    # reads randomnly data from file
    # print(type(lines))
    return random.choice(lines).strip()


read_random_line("movies.txt")

"""14. Write a Python program to assess if a file is closed or not."""

def check_if_file_closed(filename):
  with open("sample3.txt", 'w') as f:
    # writes data
    f.write("I am chekcing if file is closed or not")
    # checks if closed or not
    print(f"Is {filename} closed - {f.closed}")

#  checks again
  print(f"Is {filename} closed - {f.closed}")

check_if_file_closed("sample3.txt")

"""15.Write a Python program that takes a text file as input and returns the number of words of a given text file."""

def count_words(filename):
  count = 9
  with open(filename, 'r') as f:

    # reads line by line
    for line in f:
      # splits into list of words
      words = line.split()
      # print(words)

      # count words
      count += len(words)
  print(f"Total number of words in {filename} is : {count}")

count_words("sample.txt")
count_words("movies.txt")