# -*- coding: utf-8 -*-
"""OOP_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dLrMUXphwuOAhz2MN0L8n57r39vWr0L

1. Write a Python program to create a class representing a Circle. Include methods to calculate its area and perimeter.
"""

import math

# A class of circle including calculations such as area and perimeter of circle
class Circle:

  # initialize circle object with radius
  def __init__(self,radius):
    self.radius = radius

  # returning area of circle using formula(pi*r^2)
  def area(self):
    return math.pi * (self.radius**2)

  # returning area of perimeter using formula(2*pi*r)
  def perimeter(self):
    return 2 * math.pi * self.radius


# input radius
r = float(input("Enter radius of circle: "))
# object creation
obj1 = Circle(r)
# calling functions using object(obj1)
print("Area of circle is: ",obj1.area())
print("Area of perimeter is: ",obj1.perimeter())

"""2. Write a Python program to create a person class. Include attributes like name, country and date of birth. Implement a method to determine the person's age."""

from datetime import date

# A class of Person which includes attributes like name,country, DOB and methods to determine person's age
class Person:

  # initialize object with person's name, country, date of birth
  def __init__(self,name,country,DOB):
    self.name = name
    self.country = country
    self.DOB = DOB

  # calculate person's current age
  def calculate_age(self):
    # returns today's date
    today_date = date.today()
    # substracting today's year and birth year to calculate age
    age = today_date.year - self.DOB.year

    # if leap year
    if (today_date.month,today_date.day) < (self.DOB.month, self.DOB.day):
      age = age - 1

    return age


# Create an instance of Person_Class outside the class definition
person1 = Person("Vrushali","India",date(1997,11,28))
person2 = Person("Rutuja","India",date(1998,5,14))

print("Person1's Data: ")
print("Name:",person1.name)
print("Country:",person1.country)
print("Date of Birth:",person1.DOB)
print("Age:",person1.calculate_age())


print("\nPerson2's Data: ")
print("Name:",person2.name)
print("Country:",person2.country)
print("Date of Birth:",person2.DOB)
print("Age:",person2.calculate_age())

"""3. Write a Python program to create a calculator class. Include methods for basic arithmetic operations."""

# A class of Calculator which includes basic arithmatic operations
class Calculator:


  def __init__(self,num1,num2):
    self.num1 = num1
    self.num2 = num2

 # returns addition
  def add(self):
    return self.num1 + self.num2

 # returns subtraction
  def subtract(self):
    return self.num1 - self.num2

 # returns multiplication
  def multiply(self):
    return self.num1 * self.num2

 # returns division(returns quotient in float)
  def division(self):
    return self.num1/self.num2

 # returns modulo(returns remainder)
  def modulus(self):
    return self.num1 % self.num2

 # returns floor division(returns quotient in integer)
  def floor_division(self):
    return self.num1 // self.num2

  # returns power
  def power(self):
    return self.num1 ** self.num2

# input two numbers
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

#object creation
calculator1 = Calculator(num1,num2)

# select choices
choice = 1
while choice != 0:
  print("\nPlease select operation which you want to perform:\n"
        "0.Exit\n"
        "1.Addition\n"
        "2.Subtraction\n"
        "3.Multiplication\n"
        "4.Division\n"
        "5.Modulus\n"
        "6.Floor Division\n"
        "7.Power\n")

  # input which operation to perform
  select = int(input("Select your choice(1-7): "))


  if select == 1:
    print(f"\nAddition of {calculator1.num1} and {calculator1.num2} is =",calculator1.add())
  elif select == 2:
    print(f"\nSubtraction of {calculator1.num1} and {calculator1.num2} is =",calculator1.subtract())
  elif select == 3:
    print(f"\nMultiplication of {calculator1.num1} and {calculator1.num2} is =",calculator1.multiply())
  elif select == 4:
    print(f"\nDivision of {calculator1.num1} and {calculator1.num2} is =",calculator1.division())
  elif select == 5:
    print(f"\nmodulus of {calculator1.num1} and {calculator1.num2} is =",calculator1.modulus())
  elif select == 6:
    print(f"\nFloor Division of {calculator1.num1} and {calculator1.num2} is =",calculator1.floor_division())
  elif select == 7:
    print(f"\nPower of {calculator1.num1} and {calculator1.num2} is =",calculator1.power())
  elif select == 0:
    print("\nExited")
    break
  else:
    print("Invalid choice")

"""4. Write a Python program to create a class that represents a shape. Include methods to calculate its area and perimeter. Implement subclasses for different shapes like circle, triangle, and square."""

import math

# a class of shape which includes methods to calculate its area and perimeter.
# And subclasses for different shapes like circle, triangle, and square.
class Shape:
    def area(self): pass
    def perimeter(self): pass

# A subclass circle of Shape Class which calculates area and perimeter
class Circle(Shape):
    def __init__(self, r):
      self.r = r

    def area(self):
      return math.pi * self.r ** 2

    def perimeter(self):
      return 2 * math.pi * self.r

# A subclass Triangle of Shape Class which calculates area and perimeter
class Triangle(Shape):
    def __init__(self, s1, s2, s3, h):
        self.s1, self.s2, self.s3, self.h = s1, s2, s3, h

    def area(self):
      return 0.5 * self.s1 * self.h

    def perimeter(self):
      return self.s1 + self.s2 + self.s3

# A subclass Square of Shape Class which calculates area and perimeter
class Square(Shape):
    def __init__(self, s):
      self.s = s

    def area(self):
      return self.s ** 2

    def perimeter(self):
      return 4 * self.s

# object creation
c1 = Circle(3)
s1 = Square(2)
t1 = Triangle(4,5,6,7)

# printing area and perimeter of each shape
print(f"Circle: Area= {c1.area():.2f}, Perimeter= {c1.perimeter():.2f}")
print(f"Square: Area= {s1.area()}, Perimeter= {s1.perimeter()}")
print(f"Triangle: Area= {t1.area():.2f}, Perimeter= {t1.perimeter():.2f}")

"""5. Write a Python program to create a class representing a binary search tree. Include methods for inserting and searching for elements in the binary tree."""

# Python program of binary search tree which includes methods for inserting and searching for elements in the binary tree.

class Node:
    def __init__(self, key):
        self.left = None
        self.right = None
        self.val = key


# A utility function to insert
# a new node with the given key
def insert(root, key):
    if root is None:
        return Node(key)
    if root.val == key:
            return root
    if root.val < key:
            root.right = insert(root.right, key)
    else:
            root.left = insert(root.left, key)
    return root


# A utility function to do inorder tree traversal
def inorder(root):
    if root:
        inorder(root.left)
        print(root.val, end=" ")
        inorder(root.right)

# function to search a key in a BST
def search(root, key):

    # Base Cases: root is null or key
    # is present at root
    if root is None or root.val == key:
        return root

    # Key is greater than root's key
    if root.val < key:
        return search(root.right, key)

    # Key is smaller than root's key
    return search(root.left, key)


r = Node(15)
r = insert(r, 10)
r = insert(r, 18)
r = insert(r, 4)
r = insert(r, 11)
r = insert(r, 16)
r = insert(r, 20)
r = insert(r, 13)

# Print inorder traversal of the BST
inorder(r)

# Searching for keys in the BST
print("Found" if search(r, 19) else "\nNot Found")
print("Found" if search(r, 18) else "\nNot Found")

"""6. Write a Python program to create a class representing a stack data structure. Include methods for pushing and popping elements."""

# A class of Stack sata structure which includes methods for pushing and popping elements.
class Stack:
    def __init__(self):
        self.stack = []

  # adding elements into stack
    def push(self, element):
        self.stack.append(element)

#  deleting elements from stack
    def pop(self):
        if len(self.stack) > 0:
            return self.stack.pop()
        else:
            return None

    # def display(self):
    #   print(self.stack)


my_stack = Stack()
my_stack.push(1)
my_stack.push(2)
my_stack.push(3)

last_element = my_stack.pop()
print(f"Deleted element is : {last_element}")
# print(my_stack.display())

"""7. Write a Python program to create a class representing a linked list data structure. Include methods for displaying linked list data, inserting and deleting nodes."""

# A class of linked list data structure which includes methods for displaying linked list data, inserting and deleting nodes.
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, data):
        """Add a new node to the end of the list."""
        new_node = Node(data)
        if not self.head:
            self.head = new_node
            return

        last = self.head
        while last.next:
            last = last.next
        last.next = new_node

  # deleting elements from list
    def delete(self, key):
        """Remove the first node that matches the key."""
        temp = self.head

        # If the head node itself holds the key
        if temp and temp.data == key:
            self.head = temp.next
            return

        # Search for the key to be deleted
        prev = None
        while temp and temp.data != key:
            prev = temp
            temp = temp.next

        # If key was not present in linked list
        if temp is None:
            return

        # Unlink the node from linked list
        prev.next = temp.next

    def display(self):
        """Print the entire list."""
        temp = self.head
        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")


ll = LinkedList()
ll.insert(10)
ll.insert(20)
ll.insert(30)

print("Original List:")
ll.display()

ll.delete(20)
print("After deleting 20:")
ll.display()

"""8. Write a Python program to create a class representing a shopping cart. Include methods for adding and removing items, and calculating the total price."""

# A class of shopping cartwhich includes methods for adding and removing items, and calculating the total price.
class ShoppingCart:
    def __init__(self):
        # Initializing the cart with an empty dictionary to store item names and prices
        self.items = {}

   # adding item(name and price) into dictionary
    def add_item(self, item_name, price):
        self.items[item_name] = price
        print(f"Added '{item_name}' of Rs.{price:.2f}")

  #  removing item from cart by name
    def remove_item(self, item_name):
        if item_name in self.items:
            removed_price = self.items.pop(item_name)
            print(f"\nRemoved '{item_name}' (it's Price was: Rs.{removed_price:.2f})")
        else:
            print(f"\nItem '{item_name}' not found in the cart.")

  #  calculating total sum of items
    def calculate_total(self):
        total = sum(self.items.values())
        return total


# Creating object of shopping cart
my_cart = ShoppingCart()

# Adding items to the cart
my_cart.add_item("Laptop", 1200.00)
my_cart.add_item("Mouse", 25.50)
my_cart.add_item("Keyboard", 45.00)

# Calculating total amount
print(f"\nYour Total Price is : Rs.{my_cart.calculate_total():.2f}")

# Removing an item
my_cart.remove_item("Mouse")

# Recalculating total
print(f"\nYour Updated Total Price is: Rs.{my_cart.calculate_total():.2f}")

"""9. Write a Python program to create a class representing a stack data structure. Include methods for pushing, popping and displaying elements."""

# A class of Stack sata structure which includes methods for pushing and popping elements.
class Stack:
    def __init__(self):
        self.stack = []

  # adding elements into stack
    def push(self, element):
        self.stack.append(element)

#  deleting elements from stack
    def pop(self):
        if len(self.stack) > 0:
            return self.stack.pop()
        else:
            return None

# displaying elements from stack
    def display(self):
      return self.stack

# object creation
my_stack = Stack()
# pushing elements one by one
my_stack.push(1)
my_stack.push(2)
my_stack.push(3)

# deleting elements
last_element = my_stack.pop()
print(f"Deleted element is : {last_element}")

print(f"Remaining stack elements are : {my_stack.display()}")

"""10. Write a Python program to create a class representing a queue data structure. Include methods for enqueueing and dequeueing elements."""

# A class of Queue data structure which includes methods for enqueueing and dequeueing elements.
class Queue:
    def __init__(self):
        self.queue = []

  # adding elements
    def enqueue(self, item):
        self.queue.append(item)

  # deleting elements
    def dequeue(self):
        if len(self.queue) < 1:
            return None
        return self.queue.pop(0)

# displaying elements
    def display(self):
      return self.queue


# create an instance of the queue
my_queue = Queue()

# add some elements to the queue
my_queue.enqueue(1)
my_queue.enqueue(2)
my_queue.enqueue(3)

# remove an element from the queue
print(f"Deleted element is {my_queue.dequeue()}")

# displaying elements from queue
print(f"Remaining queue elements are {my_queue.display()}")

"""11. Write a Python program to create a class representing a bank. Include methods for managing customer accounts and transactions.

	 Create a Python class called BankAccount which represents a bank account, having as attributes: accountNumber (numeric type), name (name of the account owner as string type), balance.

	 Create a constructor with parameters: accountNumber, name, balance.

	 Create a Deposit() method which manages the deposit actions.

	 Create a Withdrawal() method which manages withdrawals actions.

	 Create an bankFees() method to apply the bank fees with a percentage of 5% of the balance account.

	 Create a display() method to display account details. Give the complete code for the BankAccount class.
"""

# A class of Bank with methods such as deposite, withdraw and ban fees and dsiplay to show details
class BankAccount:

  # initialize account number, name and balance
  def __init__(self,accountNumber, name, balance):
    self.accountNumber = accountNumber
    self.name = name
    self.balance = balance

  # function to deposite amount
  def deposite(self,amount):
    if amount > 0:
      # adding amount to the balance
      self.balance += amount
      print(f"successfully deposited {amount} in your bank account")
    else:
      print(f"Deposite amount must be positive")

  # function to withdraw amount
  def withdraw(self,amount):
    if 0 < amount <= self.balance:
      # deducting amount from balance
      self.balance -= amount
      print(f"successfully withdrew {amount} from your bank account")
    else:
      print(f"failed: Insufficient balance or Invalid amount")

#  function to apply bank fees
  def bank_fees(self):
    fees = self.balance * 0.05
    self.balance -= fees
    print(f"Bank fees of i.e 5% {fees:.2f} applied")

  # displaying details such as account number, owner name, balance
  def display(self):
    print("\n---Account Details---\n")
    print(f"Account number : {self.accountNumber}")
    print(f"Account owner name : {self.name}")
    print(f"Account balance : {self.balance}")


# object creation
customer1 = BankAccount(1012345, "vrushali", 20000)

# display details
print(customer1.display())

# deposite opearation
print(customer1.deposite(5000))

#  withdraw operation
print(customer1.withdraw(5000))

# display details
print(customer1.display())

#  withdraw operation
print(customer1.withdraw(5000))

# display details
print(customer1.display())

# apply bank fees
print(customer1.bank_fees())

# display details
print(customer1.display())

"""12. Build a flashcard using class in python. A flashcard is a card having information on both sides, which can be used as an aid in memoization. Flashcards usually have a question on one side and an answer on the other.

	Example 1:

	Approach:

	Create a class named FlashCard.
	Initialize dictionary fruits using init() method. Here you have to define fruit name as key and it's color as value. E.g., {"Banana": "yellow", "Strawberries": "pink"}
	Now randomly choose a pair from fruits by using random module and store the key in variable fruit and value in variable color.
	Now prompt the user to answer the color of the randomly chosen fruit.
	If correct print correct else print wrong.
	Output:

	welcome to fruit quiz
	What is the color of Strawberries
	pink
	Correct answer
	Enter 0, if you want to play again: 0
	What is the color of watermelon
	green
	Correct answer
	Enter 0, if you want to play again: 1
"""

import random

class FlashCard:
  def __init__(self):
    # initialize dictionary fruits - fruit names as keys and colors as values
    self.fruits = {"Banana": "yellow",
                   "Strawberries": "pink",
                   "Apple" : "red",
                   "kiwi" : "green",
                    "orange" : "orange",
                    "watermelon" : "green"}

  def fruit_quiz(self):
    print("Welcome to fruit quiz")
    while True:
      # randomly choosing fruit name as key and color as value
      # random.choice works on sequences(string,list,tuple which has index), so here converting dict keys to a list
      fruit = random.choice(list(self.fruits.keys()))
      color = self.fruits[fruit]

      # user input
      user_input = (input(f"what is the color of fruit {fruit} = ").strip().lower())

      if user_input == color.lower():
        print("Correct answer")
      else:
        print(f"Wrong answer. The correct color of {fruit} is {color}.")


      # if user wants to play again
      play_again = int(input("Enter 0, if you want to play again: "))
      if play_again != 0:
        break

# object creation
player1 = FlashCard()

# calling function
player1.fruit_quiz()

"""13. TechWorld, a technology training center, wants to allocate courses for instructors. An instructor is identified by name, technology skills, experience and average feedback. An instructor is allocated a course, if he/she satisfies the below two conditions:

	eligibility criteria:
	if experience is more than 3 years, average feedback should be 4.5 or more
	if experience is 3 years or less, average feedback should be 4 or more
	he/she should posses the technology skill for the course
	Identify the class name and attributes to represent instructors. Write a Python program to implement the class chosen with its attributes and methods.

	Note:

	Consider all instance variables to be private and methods to be public.
	An instructor may have multiple technology skills, so consider instance variable, technology_skill to be a list.
	check_eligibility(): Return true if eligibility criteria is satisfied by the instructor. Else, return false
	allocate_course(technology): Return true if the course which requires the given technology can be allocated to the instructor. Else, return false.
	Represent a few objects of the class, initialize instance variables using setter methods, invoke appropriate methods and test your program.
"""

class Instructor:
  def __init__(self):
    # initializing private variables
    self.__instructor_name = None
    self.__technology_skills = []
    self.__experience = None
    self.__average_feedback = None

  # public methods(setters) - initializing instance variable
  def set_instructor_name(self,name):
    self.__instructor_name = name

  def set_technology_skills(self,skills_list):
    self.__technology_skills = skills_list

  def set_experience(self,exp):
    self.__experience = exp

  def set_average_feedback(self,avg):
    self.__average_feedback = avg

  # getter method
  def get_technology_skills(self):
    return self.__technology_skills

  # checking eligibility criteria
  def check_eligibility(self):
    if self.__experience > 3 and self.__average_feedback >= 4.5:
      return True
    elif self.__experience <=3 and self.__average_feedback >=  4:
      return True
    else:
      False

  # Allocating course
  def allocate_course(self,technology):
    # checking eligibility first and checking technology is present in list then only allocate course
    if self.check_eligibility() and (technology in self.__technology_skills):
      return True
    return False


# object creation
inst1 = Instructor()
inst1.set_instructor_name("vrushali")
inst1.set_technology_skills(["python","java"])
inst1.set_experience(3)
inst1.set_average_feedback(4.8)

# second object
inst2 = Instructor()
inst2.set_instructor_name("Mahesh")
inst2.set_technology_skills(["AI"])
inst2.set_experience(5)
inst2.set_average_feedback(4.1)

skill = "python"
if inst1.allocate_course(skill):
  print(f"{inst1._Instructor__instructor_name} is eligible to allocate course for {skill}")
else:
  print(f"{inst1._Instructor__instructor_name} is not eligible to allocate course for {skill}")

if inst2.allocate_course(skill):
  print(f"{inst2._Instructor__instructor_name} is eligible to allocate course for {skill}")
else:
  print(f"{inst2._Instructor__instructor_name} is not eligible to allocate course for {skill}")

"""14. Write a program that uses datetime module within a class. Enter manufacturing date and expiry date of the product. The program must display the years, months and days that are left for expiry."""

from datetime import date

class Product:
    def __init__(self, mfg_date, exp_date):
        # Initialize with date objects or strings in YYYY-MM-DD format
        self.mfg_date = date.fromisoformat(mfg_date)
        self.exp_date = date.fromisoformat(exp_date)

    def calculate_remaining_time(self):
        today = date.today()

        if today >= self.exp_date:
            return "The product has already expired."

        # Calculate difference in years, months, and days
        years = self.exp_date.year - today.year
        months = self.exp_date.month - today.month
        days = self.exp_date.day - today.day

        # if days is negative
        if days < 0:
            months -= 1
            # Get the last day of the previous month
            prev_month = today.month if today.month > 1 else 12
            # Simplified approximation for days in month
            days += 30

        # if months are negative
        if months < 0:
            years -= 1
            months += 12

        return f"Time remaining for expiry is {years} Years, {months} Months, and {days} Days."

# Input data
mfg = input("Enter Manufacturing Date (YYYY-MM-DD): ")
exp = input("Enter Expiry Date (YYYY-MM-DD): ")

# Create object and display result
item = Product(mfg, exp)
print(item.calculate_remaining_time())

"""15. A university wants to automate their admission process. Students are admitted based on the marks scored in the qualifying exam. A student is identified by student id, age and marks in qualifying exam. Data are valid, if:

	Age is greater than 20
	Marks is between 0 and 100 (both inclusive)
	A student qualifies for admission, if

	Age and marks are valid and
	Marks is 65 or more
	Write a python program to represent the students seeking admission in the university.
"""

# A class of student admission process
class Student_Admission:

  # initializing student id, age, and marks
  def __init__(self, student_id, age, marks):
    self.student_id = student_id
    self.age = age
    self.marks = marks

 # checking age is valid or not
  def validate_age(self):
    # returns true if condition true otherwise false
    if self.age > 20:
      return True
    return False

 # checking marks are valid or not
  def validate_marks(self):
    if self.marks >=0 and self.marks <=100:
      if self.marks >= 65:
        return True
    return False

 # checking is student qualified or not
  def is_qualified(self):
    return self.validate_age() and self.validate_marks()


# creating object(list to store multiple student objects)
students = [
    Student_Admission(101, 25, 70),
    Student_Admission(102, 19, 67),
    Student_Admission(103, 28, 34),
    Student_Admission(104, 26,89)
]

for s in students:
  status = "Qualified" if s.is_qualified() else "Not Qualified"
  print(f"{s.student_id} is {status} for admission")

"""16. Ice-Cream Scoops and Bowl shop

	Create a class Scoop which has one public property flavor and one private proptery price. Take flavor values during object creation.

	Create a class Bowl with private prperty scoop_list which will have list of scoopd object.

	Create a method add_scoops in Bowl class which will add any no of Scoop objects given as parameter and store it in scoops_list.

	Make getter and setter method for price property.

	Make a method display to display flavour and price of each Scoop in scoop_list and print total price of the bowl by adding all flavour scoops prices.

	Make a method sold in both Scoop class and Bowl class to print no of quantity sold.
"""

class Scoop:
  # class attribute to track total sold scoops for all type of scoops
  total_scoop_sold = 0

#  initializing flavor and price
  def __init__(self, flavor):
    self.flavor = flavor #public property
    self.__price = 0.0 # private property

  # getter for price
  def get_price(self):
    return self.__price

  # setter for price
  def set_price(self,price):
    self.__price = price

  def sold_scoop(self):
    Scoop.total_scoop_sold += 1
    print(f"{self.flavor} scoop sold at {self.__price:.2f}")

class Bowl:
  # class attribute to track total count of bowl sold
  total_bowl_sold = 0

  # initializing empty list
  def __init__(self):
    self.__scoop_list = [] #private property


  # adding any number of sccop objects to the bowl
  def add_scoops(self, *scoops):
    # iterating one by one scoop from scoops
    for scoop in scoops:
      # adding one by one into private scoop_list
      self.__scoop_list.append(scoop)
      scoop.sold_scoop()
    Bowl.total_bowl_sold += 1

  # display method to display flavour and price of each Scoop in scoop_list and print total price of the bowl by adding all flavour scoops prices.
  def display(self):

    # initializing 0 to calculate total price
    total_price = 0.0

    print("\n----Your Bowl----")

    # iterating one by one scoop from list
    for s in self.__scoop_list:
      # printing flavor and price
      print(f"Flavor : {s.flavor}, Price : {s.get_price():.2f}")
      # calculating total price
      total_price += s.get_price()

  #  printing total price
    print(f"\nTotal Price is : {total_price:.2f}")

  # sold bowl
  def sold_bowl(self):
    print(f"Total bowls sold : {Bowl.total_bowl_sold}")

# object creation of scoop
s1 = Scoop("vanilla")
s1.set_price(25.00)

s2 = Scoop("chocolate")
s2.set_price(20.00)

s3 = Scoop("strawberry")
s3.set_price(23.00)

# object creation of bowl
b1 = Bowl()
b1.add_scoops(s1,s2,s3)

# display bowl cotents
b1.display()

# check total sold
b1.sold_bowl()

# ---------------------------

# object 2
print("\n")
b2 = Bowl()
b2.add_scoops(s1,s3)

b2.display()

b2.sold_bowl()
print(f"\nTotal Individual Scoop Sold : {Scoop.total_scoop_sold}")

"""17. Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100. If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. So total fare for bus instance will become the final amount = total fare + 10% of the total fare.

Note: The bus seating capacity is 50. so the final fare amount should be 5500. You need to override the fare() method of a Vehicle class in Bus class.
"""

# A base class
class Vehicle:

  #  initializing name, mileage
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100 #5000


class Bus(Vehicle):
    # Overriding the fare() method of Vehicle class
    def fare(self):
        # getting the base fare() from the parent Vehicle class
        base_fare = super().fare()
        # Adding 10% maintenance charge
        final_amount = base_fare + (base_fare * 0.10)
        return final_amount


# Creating Bus object
bus1 = Bus("School Volvo", 12, 50)

# Printing total fare
print("Total Bus fare is:", bus1.fare())

"""18. Write a Python class Employee with attributes like emp_id, emp_name, emp_salary, and emp_department and methods like calculate_emp_salary, emp_assign_department, and print_employee_details.

	Sample Employee Data:
	"ADAMS", "E7876", 50000, "ACCOUNTING"
	"JONES", "E7499", 45000, "RESEARCH"
	"MARTIN", "E7900", 50000, "SALES"
	"SMITH", "E7698", 55000, "OPERATIONS"

	Use 'assign_department' method to change the department of an employee.
	Use 'print_employee_details' method to print the details of an employee.
	Use 'calculate_emp_salary' method takes two arguments: salary and hours_worked, which is the number of hours worked by the employee. If the number of hours worked is more than 50, the method computes overtime and adds it to the salary. Overtime is calculated as following formula:
	overtime = hours_worked - 50
	Overtime amount = (overtime * (salary / 50))
"""

class Employee:
  # initializing emploee id, name, salary, dept
  def __init__(self, emp_id, emp_name, emp_salary, emp_department):
    self.emp_id = emp_id
    self.emp_name = emp_name
    self.emp_salary = emp_salary
    self.emp_department = emp_department

  # calculating emp salary
  def calculate_emp_salary(self, salary, hours_worked):
    if hours_worked > 50:
      overtime = hours_worked - 50
      overtime_amount = (overtime * (salary / 50))
      self.emp_salary += overtime_amount
      print("Salary after overtime work")
    return self.emp_salary

  # assigning department
  def assign_dept(self, dept):
    self.emp_department = dept
    return self.emp_department

  # print details
  def print_emp_details(self):
    print(f"\nEmployee ID : {self.emp_id}")
    print(f"Employee Name : {self.emp_name}")
    print(f"Employee salary : {self.emp_salary}")
    print(f"Employee Department : {self.emp_department}")
    print("\n")

emp1 = Employee("E7876", "ADAMS", 50000, "ACCOUNTING")
emp1.print_emp_details()
emp1.assign_dept("Sales")
emp1.print_emp_details()

total_pay = emp1.calculate_emp_salary(emp1.emp_salary, 60)
print(total_pay)
emp1.print_emp_details()

"""19. Write a Python class Restaurant with attributes like menu_items, book_table, and customer_orders, and methods like add_item_to_menu, book_tables, and customer_order.

	Perform the following tasks now:

	Now add items to the menu.

	Make table reservations.

	Take customer orders.

	Print the menu.

	Print table reservations.

	Print customer orders.

	Note: Use dictionaries and lists to store the data.
"""

class Restaurant:

  def __init__(self):
    # empty dictionary to store {item_name:price}
    self.menu_items = {}
    # empty list to store table numbers
    self.book_table = []
    # empty list to store list of dicts (table:tab_no, order:[items])
    self.customer_orders = []

 # add items to menu
  def add_item_to_menu(self, item_name, price):
    self.menu_items[item_name] = price

 # book table
  def book_tables(self, table_number):
    self.book_table.append(table_number)

 # take customer orders
  def customer_order(self, table_number, items):
    order = {"table": table_number, "order": items}
    self.customer_orders.append(order)


 # print menu
  def print_menu(self):
    print("\n----Menu----")
    for item, price in self.menu_items.items():
      print(f"{item} : {price}")

 # print table reservations
  def print_table_reservations(self):
    # map converts each tables numbers into string
    # join takes list of strings and merges tem into one single string separated by comma and spaces
    print(f"\n Reserved tables : {', '.join(map(str, self.book_table))}")

 # print customer orders
  def print_customer_orders(self):
    print("\n--- Customer Orders ---")
    # iterating one by one order
    for order in self.customer_orders:
      # printing table number and list of order items
      # join takes the list of orders from dictionary and merges into one sentence by comma
      print(f"Table {order['table']} ordered: {', '.join(order['order'])}")


# object creation
r1 = Restaurant()

# add items to menu
r1.add_item_to_menu("pizza",100)
r1.add_item_to_menu("burger",120)
r1.add_item_to_menu("pasta",80)

# make table reservation
r1.book_tables(3)
r1.book_tables(5)
r1.book_tables(7)

# take customer orders
r1.customer_order(3, ["pizza", "burger"])
r1.customer_order(5, ["pasta"])
r1.customer_order(7, ["pizza", "burger", "pasta"])

# print menu
r1.print_menu()
r1.print_table_reservations()
r1.print_customer_orders()

"""20. Write a Python class BankAccount with attributes like account_number, balance, date_of_opening and customer_name, and methods like deposit, withdraw, and check_balance."""

import datetime

class BankAccount:

  # initialize account number, name and balance
  def __init__(self,accountNumber, name, balance):
    self.accountNumber = accountNumber
    self.name = name
    self.balance = balance
    # Automatically set the opening date to today
    self.date_of_opening = datetime.date.today()

  # function to deposite amount
  def deposite(self,amount):
    if amount > 0:
      # adding amount to the balance
      self.balance += amount
      print(f"successfully deposited {amount} in your bank account")
    else:
      print(f"Deposite amount must be positive")

  # function to withdraw amount
  def withdraw(self,amount):
    if 0 < amount <= self.balance:
      # deducting amount from balance
      self.balance -= amount
      print(f"successfully withdrew {amount} from your bank account")
    else:
      print(f"failed: Insufficient balance or Invalid amount")

#  function to apply bank fees
  def bank_fees(self):
    fees = self.balance * 0.05
    self.balance -= fees
    print(f"Bank fees of i.e 5% {fees:.2f} applied")

  # displaying details such as account number, owner name, balance
  def display(self):
    print("\n---Account Details---\n")
    print(f"Account number : {self.accountNumber}")
    print(f"Account owner name : {self.name}")
    print(f"Date of Opening: {self.date_of_opening}")
    print(f"Account balance : {self.balance}")


# object creation
customer1 = BankAccount(1012345, "vrushali", 20000)

# display details
print(customer1.display())

# deposite opearation
print(customer1.deposite(5000))

#  withdraw operation
print(customer1.withdraw(5000))

# display details
print(customer1.display())

"""21. Write a Python class Inventory with attributes like item_id, item_name, stock_count, and price, and methods like add_item, update_item, and check_item_details."""

class Inventory:

  # initializing empty dictionary
  def __init__(self):
    self.inventory_data = {}

  # adding new items
  def add_item(self,item_id, item_name, stock_count, price):
    self.inventory_data[item_id] = {
        "item-name" : item_name,
        "stock-count" : stock_count,
        "price" : price
    }
    print(f"Item {item_name} added successfully")

  # updating inventory item(stock count or price of item)
  def update_item(self,item_id, stock_count, price):
    if item_id in self.inventory_data:
      self.inventory_data[item_id]["stock-count"] = stock_count
      self.inventory_data[item_id]["price"] = price
      print(f"Item {item_id} updated successfully")
    else:
      print(f"Item {item_id} not found")

  # printing details of item
  def check_item_details(self, item_id):
    if item_id in self.inventory_data:
      item = self.inventory_data[item_id]
      print(f"\n----Item Details----")
      print(f"Item ID : {item_id}")
      print(f"Item Name : {item["item-name"]}")
      print(f"Stock Count : {item["stock-count"]}")
      print(f"Price : {item["price"]}")
      print("\n")
    else:
      print(f"Item {item_id} not found")



items = Inventory()
items.add_item(1001, "pen", 50, 10)
items.add_item(1002, "pencil", 100, 5)
items.add_item(1003, "eraser", 20, 2)

items.check_item_details(1001)
items.check_item_details(1002)
items.check_item_details(1003)

# update stock
items.update_item(1001, 60, 20)
items.check_item_details(1001)

items.update_item(1002,50,5)
items.check_item_details(1002)