# -*- coding: utf-8 -*-
"""Python-challenges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFPr54v-qwKnXeBxe8Ef_G7sFc8C1SgT

1 - Challenge: Student Marks Analyzer

Create a Python program that allows a user to input student names along with their marks and then calculates useful statistics.
Your program should:
1. Let the user input multiple students with their marks (name + integer score).
2. After input is complete, display:
   - Average marks
   - Highest marks and student(s) who scored it
   - Lowest marks and student(s) who scored it
   - Total number of students

Bonus:
- Allow the user to enter all data first, then view the report
- Format output clearly in a report-style layout
- Prevent duplicate student names
"""

# function to collect student's data
def get_student_data():

  # taking user input no of students of data, student names and marks
  no_of_students = int(input("Enter the number of students"))
  # empty dictionary to store student's data
  student_data = {}
  for i in range(no_of_students):
    name = input(f"Enter student {i+1} name : ")

    # checking if name is empty
    if not name:
      print("Name cannot be empty")
      continue

    # checking if name already present
    if name in student_data:
      print(f"\n{name} already exists. Please use unique name.")
      name = input(f"Enter student {i+1} name : ")

    marks = float(input(f"Enter {name}'s marks : "))
    student_data[name] = marks

  return student_data


# function to print all data
def print_student_data(student_data):
  print("\n---Student's Marks----")
  # printing one by one student names and marks
  for name,marks in student_data.items():
    print(f"{name} : {marks}")

# analyzing student's data
def analyze_data(student_data):
  average_marks = sum(student_data.values()) / len(student_data)
  highest_marks = max(student_data.values())
  lowest_marks = min(student_data.values())
  total_students = len(student_data)

  top_students = [name for name, marks in student_data.items() if marks == highest_marks]
  lowest_students = [name for name, marks in student_data.items() if marks == lowest_marks]

  print("\n----- Student's Report -----")
  print(f"\n Total number of students are : {total_students}")
  print(f"\n Average Marks : {average_marks}")
  print(f"\n Highest Marks : {highest_marks}")
  print(f"\n Top Students are : {top_students}")
  print(f"\n Lowest Marks : {lowest_marks}")
  print(f"\n Bottom Students are : {lowest_students}")



def main():
  student_data = get_student_data()
  print_student_data(student_data)
  analyze_data(student_data)

if __name__ == "__main__":
  main()

""" Challenge: CLI Contact Book (CSV-Powered)

Create a terminal-based contact book tool that stores and manages contacts using a CSV file.

Your program should:
1. Ask the user to choose one of the following options:
   - Add a new contact
   - View all contacts
   - Search for a contact by name
   - Exit
2. Store contacts in a file called `contacts.csv` with columns:
   - Name
   - Phone
   - Email
3. If the file doesn't exist, create it automatically.
4. Keep the interface clean and clear.

Example:
Add Contact
View All Contacts
Search Contact
Exit

Bonus:
- Format the contact list in a table-like view
- Allow partial match search
- Prevent duplicate names from being added

"""

import json
import os

# file to store contacts
contact_file = 'contacts.json'

# function to load contacts from json file
def load_contacts():

  #checking if file exist(initially it will not exist so it returns [])
  if os.path.exists(contact_file):
    with open(contact_file, 'r') as f:
      #  converts the text inside the JSON file back into a Python list of dictionaries.
      return json.load(f)
  # if file doesn't exist, returns empty list
  return []

# function to save contacts to json file
def save_contacts(contacts):
  with open(contact_file, 'w') as f:
    json.dump(contacts, f, indent=4)

# function to add new contact
def add_contact():

  # retrieves current data from json file
  contacts = load_contacts()
  print("\n---- Add New Contact ----")
  name = input("Enter Name : ").strip()

  # prevent duplicate names
  # iterating one by one names and converts them into lower case and checks if new name matches any of them
  if any(c['Name'].lower() == name.lower() for c in contacts):
    # if mathces returns this statement
    print(f"A contact with the name '{name}' already exists.")
    return

  phone = input("Enter Phone : ").strip()

  # validate phone number length
  if len(phone) > 10:
    print("Phone number should not exceed 10 digits")
    return

  email = input("Enter Email : ").strip()

#  adds this dictionary into list
  contacts.append({"Name":name, "Phone":phone, "E-mail":email})
  # writes new contact into json file
  save_contacts(contacts)
  print(f"Contact '{name}' Added Successfully")

# function to view all contact
def view_all_contacts():
  contacts = load_contacts()
  if not contacts:
    print("\n No contacts found.")
    return

  # show data in table like view
  print("\n" + "="*60)
  print(f"{'Name':<20} | {'Phone':<15} | {'Email':<20}")
  print("-" * 60)
  for c in contacts:
    print(f"{c['Name']:<20} | {c['Phone']:<15} | {c['E-mail']:<20}") # Corrected key 'E-mail'
  print("="*60 + "\n")

# function to search for a contact by name
def search_contact():
  contacts = load_contacts()
  name = input("Enter Name to search contact : ").strip().lower()

  match = [c for c in contacts if name in c['Name'].lower()]

  if not match:
    print(f"\n No Contacts found  matching '{name}'")
  else:
    print(f"\n Found {len(match)} matching contact(s): ")
    print(f"{'Name':<20} | {'Phone':<15} | {'Email':<20}")
    print("-" * 60)
    for c in match:
      print(f"{c['Name']:<20} | {c['Phone']:<15} | {c['E-mail']:<20}")

# main menu function
def main():
  while True:
    print("\n--- Contact Book ---")
    print("\n 1. Add New Contact")
    print("\n 2. View All Contacts")
    print("\n 3. Search for a Contact by Name")
    print("\n 4. Exit")

    choice = int(input("\n Select your choice between (1-4) : "))

    if choice == 1:
      add_contact()
    elif choice == 2:
      view_all_contacts()
    elif choice == 3:
      search_contact() # Corrected function call
    elif choice == 4:
      print("Exited")
      break
    else:
      print("Invalid Choice, Please try again.")

if __name__ == "__main__":
  main()

"""**Challenge:  Personal Movie Tracker with JSON**

Create a Python CLI tool that lets users maintain their own personal movie database, like a mini IMDb.

Your program should:
1. Store all movie data in a `movies.json` file.
2. Each movie should have:
   - Title
   - Genre
   - Rating (out of 10)
3. Allow the user to:
   - Add a movie
   - View all movies
   - Search movies by title or genre
   - Exit the app

Bonus:
- Prevent duplicate titles from being added
- Format output in a clean table
- Use JSON for reading/writing structured data

"""

import json
import os

# --- 1. FILE OPERATIONS ---
# load data from file
def load_data():
    # checks file exists or not
    if os.path.exists('movies.json'):
        # if yes then Reads movies from the JSON file
        with open('movies.json', 'r') as f:
            # takes text inside file and converts into python list
            return json.load(f)
    # returns an empty list if file not found
    return []

# saves data into file
def save_data(movies):
    # writes updated movie list back to json file
    with open('movies.json', 'w') as f:
      # converts pthon list into json
        json.dump(movies, f, indent=4)

# print data
def print_table(movie_list):
  # if there are no movies in list
    if not movie_list:
        print("\n[!] No movies found.")
        return
    # Clean Table Header
    print(f"\n{'TITLE':<25} | {'GENRE':<15} | {'RATING'}")
    print("-" * 52)
    # iterating one by one and printing it
    for m in movie_list:
        print(f"{m['title']:<25} | {m['genre']:<15} | {m['rating']}/10")


# interface
def run():
    # Start by loading whatever is currently in the JSON file
    movies = load_data()

    while True:
        print("\n--- Personal Movie Tracker (JSON) ---")
        print("1. Add a Movie \n 2. View All Movies \n 3. Search movies by title or genre \n 4. Exit the App")
        choice = input("\nSelect your choice between (1-4) : ")

        if choice == '1':
            title = input("Enter Title: ")
            genre = input("Enter Genre: ")
            rating = float(input("Enter Rating (0-10): "))

            # Check for duplicates before adding
            if any(m['title'].lower() == title.lower() for m in movies):
                print(f"'{title}' is already in your database.")
            else:
                movies.append({"title": title, "genre": genre, "rating": rating})
                save_data(movies) # Save to file immediately
                print(f"Added {title} successfully! ")

        elif choice == '2':
          print_table(movies)

        elif choice == '3':
            query = input("Search Title or Genre: ").lower()
            # Filter the loaded JSON data
            # entered data and db data matches or not
            results = [m for m in movies if query in m['title'].lower() or query in m['genre'].lower()]

            # if yes
            if results:
                print("\n--- Matches ---")
                for m in results:
                    print(f"{m['title']} | {m['genre']} | {m['rating']}")
            else:
                print("No matches found.")

        elif choice == '4':
            print("Exited")
            break

# This checks if the hidden variable matches
if __name__ == "__main__":
    run()

"""**4 - Challenge: Real-Time Weather Logger (API + CSV)**

Build a Python CLI tool that fetches real-time weather data for a given city and logs it to a CSV file for daily tracking.

Your program should:
1. Ask the user for a city name.
2. Fetch weather data using the OpenWeatherMap API.
3. Store the following in a CSV file (`weather_log.csv`):
   - Date (auto-filled as today's date)
   - City
   - Temperature (in °C)
   - Weather condition (e.g., Clear, Rain)
4. Prevent duplicate entries for the same city on the same day.
5. Allow users to:
   - Add new weather log
   - View all logs
   - Show average, highest, lowest temperatures, and most frequent condition

Bonus:
- Format the output like a table
- Handle API failures and invalid city names gracefully

"""

# to send HTTP request to internet
import requests
# to parse json data
import json
# to take today's date
import datetime

# taking API KEY from openweather website
key = "63f90185a52c31b8c4ff76b1a52d7e59"

# Base URL of openweather
baseUrl = "http://api.openweathermap.org/data/2.5/weather"

# taking user input
city = input("Enter city/state name : ")

# combining baseurl, apikey and city into full web link
# ? Query Separator - instruction to filter out data after this
# appid - checks our API KEY
# taking which city we are looking for
url = baseUrl + "?appid=" + key + "&q=" + city


# sends request to the server and gets response as raw data
response = requests.get(url)
# print(response)

# To convert raw data from server into json format
res = response.json()
# print(res)
# print(json.dumps(res, indent=4))

# Checking whether the city is not found or if there is any other API error
# 200 means ok
if res.get("cod") != 200:
    print(f"Error: {res.get('message', 'Unknown error')}")

else:
    # Gets temperature in Kelvin
    tempK = res["main"]["temp"]

    # Gets humidity in percentage
    humi = res["main"]["humidity"]

    # Gets weather description
    desc = res["weather"][0]["description"]

    # Converting temperatures from Kelvin to Celcius
    tempC = tempK - 273.15

    # Printing all the results & data
    print(" Date = " , datetime.date.today())
    print(" Temperature = " + str(round(tempC, 2)) + " °C")
    print(" Humidity = " + str(humi) + "%")
    print(" Weather Description = " + str(desc))